apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply from: "../../shared.gradle"

android {
    namespace "com.google.android.accessibility.brailleime"
}

dependencies {
    implementation project(':utils')
    implementation project(':braillecommon')
    implementation project(':brailleinterfaces')
    implementation project(':brailleimeanalytics')
    implementation project(':brailletranslate')
}
